tasks:
  - name: terraform
    before: |
      source ./bin/terraform_cli_Installation.sh
      # sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      # sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      # sudo apt-get update && sudo apt-get install terraform
      source ./bin/generate_token.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      # cd /workspace
      source ./bin/install_aws_cli.sh
      # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # unzip awscliv2.zip
      # sudo ./aws/install
      # cd $THEIA_WORKSPACE_ROOT 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform